### PR TITLE
Add support for child components of Polymer components

### PR DESCRIPTION
**Pull request by bharat-srinivasan**
Add support for child components of Polymer components

### CODE REVIEW

**Comment by gkjohnson** [comment]
Hey! Thanks for your contribution!

It looks like a good change. However, subsequent changes to the child elements won't be reflected in the DOM because at the moment `shouldComponentUpdate` will return `false` if the children haven't changed, so that should probably be changed, as well.

It's also worth noting that this will only work properly at the moment with Shadow Dom enabled. It might be worth looking into what React offers again in terms of manipulating the child dom elements.

**Comment by gkjohnson** [comment]
Looks like I may have mispoken. The child elements _do_ seem to work with the shady DOM polyfill. Here's a branch I've been using to investigate a bit more:

https://github.com/gkjohnson/react-polymer-component/tree/dev/children-investigation

I've also changed the `shouldComponentUpdate()` function there to always just return `true` so the children will always update

**Comment by bharat-srinivasan** [comment]
I believe as long as child elements are also wrapped using the same PolymerComponent I do not see any issue. What do you think?

**Comment by gkjohnson** [comment]
For elements that are built with Polymer, yes. But other basic dom elements seem to work just fine without it, as well.

I'd had this disabled before because I needed it to work with Shady DOM elements and was under the impression that React wasn't playing nice with that. Maybe something changed or I was doing it wrong? I'm going to do a bit more testing and update the docs and examples before merging that branch. I'll probably be able to update the NPM package later this week. Does that work for you?

**Comment by bharat-srinivasan** [comment]
Sure will do. Thank you so much.

**Comment by gkjohnson** [comment]
I just pushed the latest version! https://github.com/gkjohnson/react-polymer-component/releases/tag/v0.1.0

Thank you again for bringing this up!

**Pull request closed without merging**
